import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { associateObservedRoad, mergeStreetGeometry, savedStreetGeometry } from '../src/utils/savedStreetGeometry';
process.env.DATABASE_URL='postgres://test:test@localhost/test';
const {dataDb}=await import('../db');
const {ROAD_SCHEMA_SQL,ROAD_LOOKUP_SQL,decodeRoadPolyline,persistRoadImport,validateRoadLocations,loadSavedStreetGeometry}=await import('../streetGeometryStore');
assert.deepEqual(decodeRoadPolyline('_vuvn@_hrxfFoK?'),[[25.03,121.53],[25.0302,121.53]],'decode actual extractor polyline format');
assert.throws(()=>decodeRoadPolyline('_'),/Truncated/);
const pg=new PGlite();
await pg.exec(ROAD_SCHEMA_SQL+`CREATE TABLE external_data_snapshots(source_key text,scope_key text,payload jsonb,content_hash text,status text,fetched_at timestamptz,checked_at timestamptz,source_updated_at timestamptz,source_version text,freshness_method text,PRIMARY KEY(source_key,scope_key));
 CREATE TABLE personal_history(id text); INSERT INTO personal_history VALUES ('preserved');`);
let fail=false;
const calls:string[]=[];
const query=async (sql:string,values?:any[])=> {calls.push(sql);if(fail && sql.startsWith('INSERT INTO external_street_geometry'))throw Error('STORAGE_WRITE_LIMIT');return pg.query(sql,values);};
(dataDb as any).query=query;
const client={query} as any;
const roads=Array.from({length:10},(_,i)=>({id:`w${i}:0:0`,name:`測試街${i}`,highway:'residential',polyline:'_vuvn@_hrxfFoK?'}));
const stamp=new Date().toISOString();
await query('BEGIN'); const inserted=await persistRoadImport(client,roads,stamp); await query('COMMIT');
assert.equal(inserted.roadCount,10);assert.equal(inserted.roadsChanged,true);
calls.length=0;
await query('BEGIN');assert.equal((await persistRoadImport(client,roads,stamp)).roadsChanged,false);await query('COMMIT');
assert.equal(calls.some(s=>s.startsWith('DELETE')),false,'unchanged roads do not consume replacement writes');
await query('BEGIN');await assert.rejects(()=>persistRoadImport(client,roads,new Date(Date.now()-86400000).toISOString()),/older/);await query('ROLLBACK');
fail=true;await query('BEGIN');await assert.rejects(()=>persistRoadImport(client,roads.map(r=>({...r,name:r.name+'新版'})),stamp),/STORAGE_WRITE_LIMIT/);await query('ROLLBACK');fail=false;
assert.equal((await pg.query<{name:string}>('SELECT name FROM external_street_geometry WHERE feature_id=$1',['w0:0:0'])).rows[0].name,'測試街0','failed import preserves previous geometry');
assert.equal((await pg.query('SELECT * FROM personal_history')).rows.length,1);
const record={coords:{lat:25.0301,lng:121.53},streetName:'測試街0',city:'臺北市',district:'大安區'};
const result=await loadSavedStreetGeometry(validateRoadLocations([record]));
assert.equal(result.dataStatus,'cached');assert.equal(result.roads.length,1);assert.ok(savedStreetGeometry(record,result.roads).paths.length);
const candidates=(await pg.query(ROAD_LOOKUP_SQL,[JSON.stringify([{lat:25.0301,lng:121.53}])])).rows as any[];
assert.equal(candidates.length,10,'bounded batch query resolves multiple locations without per-visit reads');
assert.throws(()=>validateRoadLocations(Array(201).fill(record)),/1–200/);
assert.throws(()=>validateRoadLocations([{...record,coords:{lat:NaN,lng:121}}]),/Invalid/);
const unnamed={id:'mapped-unnamed',name:'',coords:[[25.03,121.53],[25.0302,121.53]] as [number,number][]};
const observed=associateObservedRoad(record,[unnamed]);assert.ok(observed);assert.equal(observed.name,'');
const cached=mergeStreetGeometry([],[observed]);assert.ok(savedStreetGeometry(record,cached).paths.length,'unnamed actual lane preserves coordinate association after cache/reload');
assert.ok(associateObservedRoad(record,[{...unnamed,name:'另一條路；測試街0'}]),'real semicolon-separated OSM road aliases match');
assert.equal(associateObservedRoad(record,[unnamed,{...unnamed,id:'ambiguous',coords:[[25.03,121.53001],[25.0302,121.53001]]}]),null,'ambiguous junction/parallel lanes cannot invent a match');
assert.equal(associateObservedRoad({...record,streetName:'龍田里'},[unnamed]),null,'neighbourhood assessments cannot be painted as one street');
await pg.close();await dataDb?.end();
console.log('Persisted street geometry passed: real PostgreSQL batch reads, repeat/rollback preservation, bounded inputs, unnamed lane association and ambiguity rejection.');
